<?php

use Illuminate\Support\Str;

return [
    'default' => 'mysql',
    'connections' => [
        'sqlite' => [
            'driver' => 'sqlite',
            'url' => null,
            'database' => database_path('database.sqlite'),
            'prefix' => '',
            'foreign_key_constraints' => true,
        ],
        'mysql' => [
            'driver' => 'mysql',
            'url' => null,
            'host' => config('api.mysql.host'),
            'port' => config('api.mysql.port'),
            'database' => config('api.mysql.database'),
            'username' => config('api.mysql.username'),
            'password' => config('api.mysql.password'),
            'unix_socket' => '/tmp/mysql.sock',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
        'mariadb' => [
            'driver' => 'mariadb',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => env('DB_CHARSET', 'utf8mb4'),
            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
        'pgsql' => [
            'driver' => 'pgsql',
            'url' => null,
            'host' => config('api.pgsql.host'),
            'port' => config('api.pgsql.port'),
            'database' => config('api.pgsql.database'),
            'username' => config('api.pgsql.username'),
            'password' => config('api.pgsql.password'),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],
        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'url' => null,
            'host' => config('api.sqlsrv.host'),
            'port' => config('api.sqlsrv.port'),
            'database' => config('api.sqlsrv.database'),
            'username' => config('api.sqlsrv.username'),
            'password' => config('api.sqlsrv.password'),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            // 'encrypt' => env('DB_ENCRYPT', 'yes'),
            // 'trust_server_certificate' => env('DB_TRUST_SERVER_CERTIFICATE', 'false'),
        ],

    ],
    'migrations' => [
        'table' => 'migrations',
        'update_date_on_publish' => true,
    ],
    'redis' => [
        'client' => 'phpredis',
        'options' => [
            'cluster' => 'redis',
            'prefix' => Str::slug(config('app.name'), '_').'_database_',
        ],
        'default' => [
            'url' => null,
            'host' => config('api.redis.host'),
            'username' => config('api.redis.username'),
            'password' => config('api.redis.password'),
            'port' => config('api.redis.port'),
            'database' => '0',
        ],
        'cache' => [
            'url' => null,
            'host' => config('api.redis.host'),
            'username' => config('api.redis.username'),
            'password' => config('api.redis.password'),
            'port' => config('api.redis.port'),
            'database' => '1'
        ],
    ],
];
